"""Copy the custom layers the teacher model needs out of EQTransformer's EqT_utils.py.

Usage: python scripts/vendor_eqt_layers.py <path/to/EqT_utils.py> app/eqt_layers.py
"""
import ast
import sys
from pathlib import Path

WANTED = ["f1", "LayerNormalization", "FeedForward", "SeqSelfAttention"]

HEADER = '''"""Custom layers of the original EQTransformer, needed to load the teacher model.

Copied verbatim from EQTransformer/core/EqT_utils.py
(https://github.com/smousavi05/EQTransformer), MIT License,
Copyright (c) 2020-2025 S. Mostafa Mousavi.
Generated by scripts/vendor_eqt_layers.py - do not edit by hand.
"""
import numpy as np  # noqa: F401
from tensorflow import keras
from tensorflow.keras import backend as K  # noqa: F401
from tensorflow.keras.layers import InputSpec  # noqa: F401

'''


def main(src_path: str, out_path: str) -> None:
    src = Path(src_path).read_text(encoding="utf-8")
    tree = ast.parse(src)
    nodes = {
        n.name: n
        for n in tree.body
        if isinstance(n, (ast.FunctionDef, ast.ClassDef)) and n.name in WANTED
    }
    missing = set(WANTED) - nodes.keys()
    if missing:
        raise SystemExit(f"Not found in {src_path}: {sorted(missing)}")
    body = "\n\n\n".join(ast.get_source_segment(src, nodes[name]) for name in WANTED)
    footer = f"\n\n\nCUSTOM_OBJECTS = {{name: globals()[name] for name in {WANTED!r}}}\n"
    Path(out_path).write_text(HEADER + body + footer, encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
